production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  url: <%= ENV["DATABASE_URL"] %>
  
  # Alternative configuration if not using DATABASE_URL
  # database: golf_n_vibes_production
  # username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  # password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  # host: <%= ENV.fetch("DB_HOST", "localhost") %>
  # port: <%= ENV.fetch("DB_PORT", "5432") %>
  
  # Production optimizations
  prepared_statements: true
  advisory_locks: true
  
  # Connection pool settings
  checkout_timeout: 5
  reaping_frequency: 10
  
  # SSL settings for managed databases
  sslmode: <%= ENV.fetch("DB_SSL_MODE", "prefer") %>
  
  # Timeout settings
  connect_timeout: 10
  read_timeout: 10
  write_timeout: 10
