name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: golf-n-vibes-spree
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpq-dev nodejs yarn

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/spree-golf:${{ github.sha }}
        file: ./Dockerfile
        context: .

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/spree-golf:${{ github.sha }}

    - name: Configure Web App Environment
      run: |
        az webapp config appsettings set --resource-group golf-n-vibes-rg --name ${{ env.AZURE_WEBAPP_NAME }} --settings \
          RAILS_ENV=production \
          SECRET_KEY_BASE="${{ secrets.SECRET_KEY_BASE }}" \
          RAILS_SERVE_STATIC_FILES=true \
          RAILS_LOG_TO_STDOUT=true \
          SPREE_ADMIN_EMAIL=admin@golfnvibes.com \
          SPREE_ADMIN_PASSWORD=GolfNVibes2024! \
          STORE_NAME="Golf N Vibes" \
          STORE_EMAIL=info@golfnvibes.com
      continue-on-error: true
      
    - name: Wait for Deployment
      run: |
        echo "Deployment completed! Your Golf N Vibes store should be available at:"
        echo "https://golf-n-vibes-spree.azurewebsites.net"
        echo "Admin panel: https://golf-n-vibes-spree.azurewebsites.net/admin"
        echo "Note: Database setup will run automatically when the container starts."
