name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: golf-n-vibes-spree
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpq-dev nodejs yarn

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/spree-golf:${{ github.sha }}
        file: ./Dockerfile
        context: .

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/spree-golf:${{ github.sha }}

    - name: Run Database Migrations
      run: |
        az webapp config appsettings set --resource-group golf-n-vibes-rg --name ${{ env.AZURE_WEBAPP_NAME }} --settings RAILS_ENV=production
        az webapp ssh --resource-group golf-n-vibes-rg --name ${{ env.AZURE_WEBAPP_NAME }} --instance 0 "cd /app && bundle exec rails db:migrate"
      continue-on-error: true
      
    - name: Setup Sample Data (First Deployment Only)
      run: |
        az webapp ssh --resource-group golf-n-vibes-rg --name ${{ env.AZURE_WEBAPP_NAME }} --instance 0 "cd /app && bundle exec rails spree_sample:load"
      continue-on-error: true
